Flere ændringer, stavefejl og bug fixes
BetterLectio/betterLectio pull request #178
Opened 2023-08-16 13:22 UTC by asger-finding

### Tilføjede et nyt mørkt standardtema: "neddæmpet"

Følte at alle de mørke farvetemaer var for skrigende, ledte efter noget mere klassisk og har flere enige i det i min klasse.

### Stort refactor på elevlist-siden

Værktøjet ligner sig selv, men har nu en klasse-sortering. Har fikset ligegyldige `async`-expressions og genskrevet nogle ting.
Det er nu muligt at søge gennem alle klasser eller en specifik en, og koden er mere læselig.

### Nedtonet outline for skemaet

Når mørkt tema var valgt og man åbnede skemaet, var outlinen meget gennemtrængende og tydelig, og trak væk fra udtrykket af resten af siden.

Jeg har tilføjet *lidt* styling i app.css. Jeg ved ikke hvordan det spiller ind med daisyUI/tailwind, og om det hellere skulle hardcodes til hvert element over svelte.

Ændringen fjerner også en outline for tyk på skemaet (border-b-0 på allDay)

### Stilren hover-linje på tekstafsnit

Har tilføjet `hover:rounded-l-none` til hover-elementer som f.eks. Ulæste Beskeder og sektionerne i Lectio. Dette giver et pænere, mere skarpt udtryk.

2023-08-16 16:04 UTC, jona799t requested changes
Det ser rigtig godt ud. Jeg er helt klart enig i at der helt klart manglede et mere "neddæmpet" tema. Den nye elevside er også en forbedring. 

Det eneste er et lille problem med klassesorteringen. Nogen elever på vores skole har parentes i deres navn fordi de har et andet navn de hellere vil kaldes end deres officielle. Lige nu tror koden at deres andet navn er deres klasse.
Har lagt et hurtigt fiks ind i kommentarene, men du er velkommen til selv at finde på et.

![image](https://github.com/BetterLectio/betterLectio/assets/70392256/35f1d07b-0a97-4c29-9be3-d6556c0042fd)

2023-08-17 07:35 UTC, asger-finding commented
Så er den løst :)

Nu bruger vi $informationer.klasser til at lave klasse-dropdownen, og jeg har fikset parsing af brugernavne.

2023-08-17 08:29 UTC, victorDigital approved these changes
ser godt ud ifølge mig!

2023-08-17 09:31 UTC, asger-finding commented
Har lige proppet nogle flere ændringer til skemaet på. Meget gerne tjem dem ud :)

![image](https://github.com/BetterLectio/betterLectio/assets/49583904/b5f3763a-2476-408c-831a-faa9b191c74c)

![image](https://github.com/BetterLectio/betterLectio/assets/49583904/f06cc2db-e086-4d07-af33-2fcc060d0760)

2023-08-17 09:43 UTC, jona799t approved these changes
Det ser godt ud!

2023-08-17 09:44 UTC, merged