Refactors og fixes
BetterLectio/betterLectio pull request #183
Opened 2023-08-23 18:24 UTC by asger-finding

refactor: fjern ugyldige await expressions
refactor: change new theme button
refactor: global search rewrite
refactor: change sanitize-html module to dompurify
fix: handle errors correctly by displaying a warning as was intended
fix: more strict type checking
refactor: more verbose variables
fix: remove most meaningless asynchrony
fix: address some todo's and fixme's
fix: address some accessibility warnings (but not all yet)
fix: valentine theme was rounding button corners
refactor: change eslint config to yaml
refactor: remove all prettier
fix: attempt to address most console warnings and errors
fix: fix small typos

2023-08-24 08:07 UTC, jona799t commented
Kigger på det når jeg kommer hjem

2023-08-25 22:08 UTC, jona799t requested changes
Der er et problem med brugen af hold oversætteren i ``src/routes/skema/+page.svelte``.
Det første problem er bare en lille typo. ``modul.hold.id`` skal ændres til ``modul.hold_id``.
Der er dog et andet problem er at alt bliver undefined indtil man reloader da  ``$fag[modul.hold_id] `` ikke er blevet defineret inden modulet bliver tilføjet til skemaet.

Det letteste fix er bare at gøre addSkemaToCalendar() til async og så ``await holdOversætterNy(modul.hold_id)``

![image](https://github.com/BetterLectio/betterLectio/assets/70392256/1a5e054a-41b6-4eb0-af26-db214ae3e5c3)

2023-08-25 22:08 UTC, jona799t commented on src/routes/skema/+page.svelte
> +	function addSkemaToCalendar(_skema) {
```javascript
async function addSkemaToCalendar(_skema)
```

2023-08-25 22:08 UTC, jona799t commented on src/routes/skema/+page.svelte
> +				holdOversætterNy(modul.hold.id).then(_fag => {
```javascript
const _fag = await holdOversætterNy(modul.hold_id);
$fag[modul.hold_id] = _fag === "Andet" ? modul.hold : _fag;
```

2023-08-27 10:33 UTC, asger-finding commented on src/routes/skema/+page.svelte
> +				holdOversætterNy(modul.hold.id).then(_fag => {
Gad gerne bruge Promise.all så vi ikke får await i loops men løsningen duer, vi kan altid kigge tilbage på det senere

2023-08-27 10:41 UTC, asger-finding commented
Så er ting oppe at køre igen, tjek lige efter igen <3

2023-08-28 06:31 UTC, victorDigital commented
Jeg får stadig samme error:
![image](https://github.com/BetterLectio/betterLectio/assets/99267380/c3e1b665-0951-428d-b418-f3cc9c90de9e)
![image](https://github.com/BetterLectio/betterLectio/assets/99267380/5c8aae39-f1d0-4a69-bb4e-a3a39f42252c)

Udover det ser det godt ud! 👌👏

2023-08-28 07:19 UTC, asger-finding commented
@victorDigital Før var der dusinvis af fejl. Jeg tror måske den her error er på lectio's side.

Den var bare ikke spottet før, da fejlene ikke kunne ses direkte på siden. Måske bør vi lade hvert call til http's `get` selv bestemme om de ville lave en notifikation, i stedet for at implementere det direkte i `get`? Fejlene er jo rimeligt ligegyldige for brugerne, bare ikke for os

PS: Måske bør vi ikke sende et backtrace fra proxien, det kan kun føre til sikkerhedsproblemer (selvom proxien er open source)

2023-08-29 08:33 UTC, jona799t commented
Den ene fejl er vidst bare fordi der er et modul som ikke er et fag.
Tror jeg har tid til at få kigget på resten af pull requesten når jeg kommer hjem

2023-08-29 19:48 UTC, jona799t approved these changes
Har lige skimmet det igennem. Godt arbejde!

2023-08-29 19:48 UTC, merged